image: hseeberger/scala-sbt

variables:
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/.sbtboot -Dsbt.boot.directory=sbt-cache/.boot -Dsbt.ivy.home=sbt-cache/.ivy"

cache:
  key: "$CI_BUILD_REF_NAME"
  untracked: true
  paths:
    - "apt-cache/"
    - "set/sbt-cache/.ivy/cache"
    - "set/sbt-cache/.boot"
    - "set/sbt-cache/.sbtboot"
    - "set/sbt-cache/target"

stages:
  - lint

before_script:
  ## Insall OpenJFX requirement
  - export APT_CACHE_DIR="$(pwd)/apt-cache"
  - mkdir -p ${APT_CACHE_DIR}
  - apt-get -o dir::cache::archives=${APT_CACHE_DIR} update -y
  - apt-get -o dir::cache::archives=${APT_CACHE_DIR} install openjfx -y

lint:
  stage: lint
  script:
    - cd set
    - sbt clean scalastyle
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - set/target/scalastyle-result.xml
