version: 2
jobs:
  build:
    docker:
      - image: hseeberger/scala-sbt
    steps:
      - checkout
      - run:
          name: Install Required Packages
          command: |
              apt-get update
              apt install -y openjfx fakeroot
      - run:
          name: Debian Pacakge
          command: |
              cd set
              sbt debian:packageBin
              cp target/*.deb /tmp/packages
      - store_artifacts:
          path: /tmp/packages
