version: 2
jobs:
  build:
    docker:
      - image: hseeberger/scala-sbt
    steps:
      - checkout
      - run:
          name: Install Required Packages
          command: |
              apt-get update
              apt install -y openjfx fakeroot
      - restore_cache:
          keys:
            - ivy-cache
      - run:
          name: Debian Pacakge
          command: |
              cd set
              sbt debian:packageBin
              mkdir -p /tmp/packages
              cp target/*.deb /tmp/packages
      - save_cache:
          key: ivy-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
      - store_artifacts:
          path: /tmp/packages

workflows:
  version: 2
  workflow:
    jobs:
    - build
